version: '3.8'
services:
  koala-activity-consumer:
    image: koala-activity-consumer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DOTNET_ENVIRONMENT=Development